<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
    <Title>Hybrid_Chat Network Engine</Title>
    <Company>Architectural Engineering Corp</Company>
    <Description>Multi-Client TCP/UDP Hybrid Sync Chat Environment</Description>
  </PropertyGroup>

</Project>